### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by ariscop**
This brings the windows port back into almost working condition, more work would be needed to make it actually usable

Other changes:
The ircd is now compiled into libelemental.so, this was needed to support module linking on windows and should in general be more reliable.

Libratbox is no longer linked statically

LTDL is used for module loading now, which is why there's no LoadLibrary call anywhere, also removes a bunch of code from module.c

### CODE REVIEW

**Comment by Xe** [comment]
I did not think this was possible.

**Comment by AppleDash** [comment]
@Xe Me neither.

**Comment by Xe** [comment]
```
libtoolize: Consider using `AC_CONFIG_AUX_DIR([extra/libltdl/config])' in configure.ac.
libtoolize: Consider using `AC_CONFIG_MACRO_DIR([extra/libltdl/m4])' in configure.ac.
```

**Comment by ariscop** [comment]
@Xe libtoolize (which recommends and installs those directories) runs after autoconf, if you add those it errors

**Comment by ariscop** [comment]
Still todo:
Leak in sslproc and rb_helper, two winsock handles per spawn, haven't figured out from where yet
ssld gets killed real quick, the ircd considers it dead, don't know if it works besides that yet

**Comment by ariscop** [comment]
ssld/bandb work, now it's just a matter of moving platform-specific stuff to where it should be, src/platform instead of random ifdefs throughout the entire codebase

**Comment by ariscop** [comment]
Merge ready imo
m_stats breaks out of the box but if anyone's actually USING this then that's their fault

**Comment by Xe** [comment]
Define "breaks"?

**Comment by ariscop** [comment]
@Xe Can't compile on windows, printf specifiers that depend on %z (doesn't exist), %ll (is %i64 on msvc) and uses getrusage
Comment it out in modules/Makefile.am and everything else builds fine, i just couldn't be bothered fixing the long-long printf thing

**Comment by ariscop** [comment]
<ariscop> Xena, yay/nay on pr 118?
<ariscop> the windows support one
<Xena> why not

**Pull request merged**
