### PR TITLE
OSX fixes

### PR DESCRIPTION
**Pull request by Xe**
This fixes some things such that elemental once again can be compiled and run on Mac OSX. My local dev machine is a cylinder mac pro (2013) with OSX 10.10.5. All basic functionality is tested and known to work. It is not suggested to use OSX in production.

### CODE REVIEW

**Comment by ariscop** [comment]
Waiting on a response from the support email before osx builds will actually work, so the travis.yml is untested

**Comment by ariscop** [comment]
026c632 works, but the tests all time out

**Comment by ariscop** [comment]
Port is fine, osx vm's on travis have a dns problem
Good to merge imo

**Comment by Xe** [comment]
+1

**Pull request merged**
