### PR TITLE
Channel operation tests

### PR DESCRIPTION
**Pull request by Xe**
PR for #153 

Not ready to merge yet, this PR is intended as a discussion thread for the implementation of this. Any help on this is welcome.

### CODE REVIEW

**Comment by Xe** [comment]
Blocked on #164

**Comment by Xe** [comment]
Actually it's not, can just add

```tcl
# XXX HACK to work around #164
client:
```

to tests that #164 breaks.

**Comment by Xe** [comment]
@ariscop is it okay to leave the concurrent tests to 1 for now?

**Comment by ariscop** [comment]
for now, yeah

**Pull request merged**
