### PR TITLE
Build system overhaul

### PR DESCRIPTION
**Pull request by ariscop**

### CODE REVIEW

**Comment by ariscop** [comment]
clang picks up some warnings that gcc doesn't, both are absurdly noisy right now though

**Comment by ariscop** [comment]
Minor case of scope creep

**Comment by Xe** [comment]
yay automake!

**Comment by ariscop** [comment]
I'm calling this done for now, unless any major problems pop up, some hairy code in both configure.ac files but it's held together thus far.

Only really been tested on fedora and ubuntu, *bsd may or may not work anymore, and windows support probably doesn't compile anyway.
There's so much less build system to maintain that ports should be simpler should anyone want them.

**Comment by Xe** [comment]
if this build passes, feel free to merge #73 as well, it will need some rebasing.

**Comment by Xe** [comment]
oh, a little patch to place on the top:

```diff
diff --git a/Dockerfile b/Dockerfile
index d1a6939..499287b 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -3,14 +3,14 @@ MAINTAINER Xena <xena@yolo-swag.com>

 # Update base system
 RUN apt-get update && apt-get upgrade -yq && \
-    apt-get -yq install build-essential autoconf libssl-dev flex bison libsqlite3-dev && \
+    apt-get -yq install build-essential autoconf libssl-dev flex bison libsqlite3-dev automake && \
     adduser --system --home /home/ircd ircd && \
     mkdir /home/ircd/src && \
     chmod 777 /home/ircd/src

 ADD . /home/ircd/src

-RUN cd /home/ircd/src; ./configure --prefix=/home/ircd/run ; make ; make install
+RUN cd /home/ircd/src; ./autogen.sh && ./configure --prefix=/home/ircd/run ; make ; make install

 ADD doc/example.conf /home/ircd/run/etc/ircd.conf
 ADD extra/runit/ /etc/service/ircd/
```

**Pull request merged**
